### ISSUE TITLE
Repetition of categories in corresponding vocab files

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS#38]
I searched for the category "coordinateSpace" and found it 3-times in the [categories file](https://github.com/openMetadataInitiative/openMINDS/blob/main/vocab/categories.json). Maybe introduce with the update of the namespace, @Raphael-Gazzotti?

**Comment by Raphael-Gazzotti** [comment]
I may be misunderstanding the issue, but it seems "coordinateSpace" appears only once per version (latest, v4.0, v3.0).

**Comment by UlrikeS91** [comment]
Yeah, I'm sorry. I forgot about that 😆 I think I have been working too much with the properties and just assumed similar structures which obviously does not make any sense.
